# Generated by Django 4.2.9 on 2024-01-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
        migrations.AlterModelOptions(
            name='reguser',
            options={'verbose_name': 'Regular User', 'verbose_name_plural': 'Regular Users'},
        ),
    ]
