# Generated by Django 4.2.9 on 2024-01-31 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_adminuser_options_alter_reguser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuserprofile',
            options={'verbose_name': 'Admin User Profile', 'verbose_name_plural': 'Admin User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='reguserprofile',
            options={'verbose_name': 'Regular User Profile', 'verbose_name_plural': 'Regular User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
